name: NASA APOD Image Downloader

on:
  workflow_dispatch:

jobs:
  download-nasa-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch APOD JSON from NASA API
        run: |
          curl "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.NASA_API_KEY }}" -o nasa_apod.json

      - name: Extract image URL and download if image
        run: |
            IMAGE_URL=$(jq -r '.hdurl' nasa_apod.json)
            echo "Downloading image from: $IMAGE_URL"
            curl "$IMAGE_URL" -o apod_image.jpg         

      - name: Upload JSON and image (if exists) as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nasa-apod-assets
          path: |
            nasa_apod.json
            apod_image.jpg
        continue-on-error: true  # in case image isn't downloaded
